version: '3.4'

services:

  lpvs:
    build:
      context: .
    image: ghcr.io/samsung/lpvs:latest
    restart: always
    ports:
      - "7896:7896"
    environment:
      ## Database Configuration
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/lpvs
      - spring.datasource.username=root
      - spring.datasource.password=
      - spring.jpa.properties.hibernate.default_schema=lpvs
      ## Github data for fetching code
      - github.login=
      - github.token=
      - github.api.url=https://api.github.com
      - github.secret=LPVS

    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - lpvs

  mysqldb:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - ./src/main/resources/database_dump.sql:/docker-entrypoint-initdb.d/init.sql # init for creating db lpvs with predifined tables
    networks:
      - lpvs

  ngrok:
    image: wernight/ngrok
    command: ngrok http lpvs:7896
    ## NGROK Auth token
    environment:
      - NGROK_AUTHTOKEN=
    ports:
      - "4040:4040"
    depends_on:
      - lpvs
    networks:
      - lpvs

networks:
  lpvs:
