site_name: License Pre-Validation Service
site_url: https://samsung.github.io/LPVS/
site_description: License Pre-Validation Service (LPVS) Documentation

repo_url: https://github.com/Samsung/LPVS
edit_uri: blob/main/doc/docs/

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  locale: en
  highlightjs: true

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      clickable_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - neoteroi.mkdocsoad:
      use_pymdownx: true

nav:
  - Home: index.md
  - Quick Start Guide: quick-start-guide.md
  - User Guide:
      - User guide: user-guide/README.md
      - Service mode:
          - GitHub webhook configuration: user-guide/service/webhook.md
          - Run service using pre-built Docker image: user-guide/service/docker.md
          - Build and run service from the source code:
            - Prerequisites:
              - Scanner installation: user-guide/service/scanner.md
              - Database configuration: user-guide/service/database.md
            - Build and run service: user-guide/service/build-and-run.md
      - Command line mode:
          - Single scan of the pull request: user-guide/cli/cli_pr.md
          - Single scan of local files: user-guide/cli/cli_file.md
      - Configuration:
          - Configuration options: user-guide/config/options.md
          - Database customization: user-guide/config/database.md
  - Developer Guide:
      - Developer guide: dev-guide/README.md
      - Contributing guide: dev-guide/contributing.md
      - Testing policy: dev-guide/testing-policy.md
      - Code review requirements: dev-guide/code-review-requirements.md
      - API reference: dev-guide/api.md
      - Integration guide: dev-guide/integration.md
  - About:
      - License: about/license.md
      - Releases: about/releases.md

extra_css:
  - css/extra.css
  - css/mkdocsoad.css

exclude_docs: |
  *.py

use_directory_urls: true

copyright: Copyright &copy; 2024, Samsung Electronics Co., Ltd. All rights reserved.
