name: Generate and Publish Javadoc

on:
  push:
    branches:
      - main

jobs:
  generate-and-publish-javadoc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28

      - name: Set up JDK
        uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build and generate Javadoc
        run: |
          mvn clean install javadoc:javadoc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/apidocs
