name: Build & Publish Documentation

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  generate-and-publish-mkdocs:
    name: Build and Publish Updated Docs
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Install docs required dependencies
        run: pip install --require-hashes -r doc/requirements-docs.txt
      - name: Build website
        run: |
          cd doc
          mkdocs build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/site
